/**
 * Default maintenance templates organized by category.
 * Used both for DB seeding and for the signup flow to auto-create tasks.
 */
export const CATEGORIES = [
  { name: 'HVAC', slug: 'hvac', icon: 'thermometer', color: '#1e3a5f', description: 'Heating, ventilation, and air conditioning systems' },
  { name: 'Water Heater', slug: 'water-heater', icon: 'droplets', color: '#dd6b20', description: 'Hot water heater maintenance and care' },
  { name: 'Pool', slug: 'pool', icon: 'waves', color: '#2c5282', description: 'Swimming pool equipment and water chemistry' },
  { name: 'Plumbing', slug: 'plumbing', icon: 'wrench', color: '#2b6cb0', description: 'Pipes, fixtures, valves, and water supply systems' },
  { name: 'Electrical', slug: 'electrical', icon: 'zap', color: '#d69e2e', description: 'Electrical systems, outlets, panels, and safety devices' },
  { name: 'Septic System', slug: 'septic', icon: 'layers', color: '#744210', description: 'Septic tank, drain field, and wastewater management' },
  { name: 'Roof & Gutters', slug: 'roof-gutters', icon: 'home', color: '#718096', description: 'Roofing, gutters, downspouts, and drainage' },
  { name: 'Appliances', slug: 'appliances', icon: 'settings', color: '#4a5568', description: 'Major household appliances and their maintenance' },
  { name: 'Exterior & Foundation', slug: 'exterior', icon: 'shield', color: '#276749', description: 'Siding, foundation, driveway, deck, and outdoor structures' },
  { name: 'Garage Door', slug: 'garage-door', icon: 'square', color: '#6b46c1', description: 'Garage door system, opener, tracks, and hardware' },
];

export const TEMPLATES = {
  hvac: [
    { name: 'Replace Air Filter', description: 'Replace or clean HVAC air filter. Check for dust buildup and proper fit.', interval_days: 90, priority: 'high' },
    { name: 'Clean Supply Vents', description: 'Remove vent covers and wash. Vacuum inside ducts.', interval_days: 90, priority: 'medium' },
    { name: 'Check Thermostat Battery', description: 'Replace thermostat batteries. Verify programming for season.', interval_days: 180, priority: 'low' },
    { name: 'Clean Condensate Drain', description: 'Pour bleach/vinegar down condensate drain to prevent clogs.', interval_days: 90, priority: 'medium' },
    { name: 'Inspect Outdoor Unit', description: 'Clear debris within 2ft of condenser. Gently hose coils.', interval_days: 180, priority: 'medium' },
    { name: 'Professional Tune-Up', description: 'Schedule professional HVAC tune-up. AC in spring, heating in fall.', interval_days: 365, priority: 'high' },
    { name: 'Check Ductwork for Leaks', description: 'Inspect visible ductwork for gaps or damaged insulation.', interval_days: 365, priority: 'medium' },
    { name: 'Test CO Detectors', description: 'Test all CO detectors near HVAC equipment. Replace batteries annually.', interval_days: 180, priority: 'high' },
  ],
  'water-heater': [
    { name: 'Test T&P Relief Valve', description: 'Lift valve lever — water should flow briefly then stop.', interval_days: 180, priority: 'high' },
    { name: 'Flush Sediment', description: 'Drain 2-3 gallons until water runs clear to remove sediment.', interval_days: 180, priority: 'high' },
    { name: 'Check Anode Rod', description: 'Inspect sacrificial anode rod. Replace if thin or calcium-coated.', interval_days: 365, priority: 'medium' },
    { name: 'Inspect for Leaks', description: 'Check connections, tank base, and T&P discharge pipe for water.', interval_days: 90, priority: 'medium' },
    { name: 'Check Temperature Setting', description: 'Verify thermostat at 120°F for safety and efficiency.', interval_days: 180, priority: 'low' },
    { name: 'Inspect Venting (Gas Units)', description: 'Check flue and venting for blockages or corrosion.', interval_days: 365, priority: 'high' },
    { name: 'Clean Intake Filter (Tankless)', description: 'Clean inlet water filter screen. Check for scale buildup.', interval_days: 90, priority: 'medium' },
  ],
  pool: [
    { name: 'Test Water Chemistry', description: 'Test pH, chlorine, alkalinity, and cyanuric acid. Adjust as needed.', interval_days: 7, priority: 'high' },
    { name: 'Skim & Empty Baskets', description: 'Skim surface debris. Empty skimmer and pump strainer baskets.', interval_days: 3, priority: 'medium' },
    { name: 'Brush Walls & Floor', description: 'Brush pool surfaces to prevent algae. Focus on corners and shade.', interval_days: 7, priority: 'medium' },
    { name: 'Vacuum Pool', description: 'Vacuum floor manually or run automatic cleaner.', interval_days: 7, priority: 'medium' },
    { name: 'Backwash/Clean Filter', description: 'Backwash when pressure rises 8-10 PSI above clean baseline.', interval_days: 30, priority: 'high' },
    { name: 'Check Water Level', description: 'Keep water at mid-skimmer. Too low damages pump.', interval_days: 7, priority: 'low' },
    { name: 'Inspect Pool Equipment', description: 'Check pump, filter, heater for leaks or unusual noises.', interval_days: 30, priority: 'medium' },
    { name: 'Shock the Pool', description: 'Super-chlorinate to break down chloramines. Do in the evening.', interval_days: 14, priority: 'high' },
    { name: 'Clean Tile Line', description: 'Scrub waterline tile to remove calcium and oil deposits.', interval_days: 30, priority: 'low' },
    { name: 'Seasonal Opening/Closing', description: 'Full seasonal service: cover, equipment, chemistry, prime system.', interval_days: 182, priority: 'high' },
  ],
  plumbing: [
    { name: 'Exercise Main Water Shut-Off Valve', description: 'Turn the main shut-off valve fully closed then open again. Prevents it from seizing up so it works when you actually need it.', interval_days: 180, priority: 'high' },
    { name: 'Exercise Individual Fixture Shut-Offs', description: 'Turn each sink, toilet, and appliance shut-off valve closed and open. Check for drips or stiffness.', interval_days: 180, priority: 'medium' },
    { name: 'Check Under Sinks for Leaks', description: 'Inspect under all kitchen and bathroom sinks for moisture, drips, water stains, or mold. Check supply lines and drain connections.', interval_days: 90, priority: 'high' },
    { name: 'Inspect Toilet Flappers', description: 'Check toilet flappers for wear, warping, or mineral buildup. A leaking flapper can waste 200+ gallons per day. Replace if it doesn\'t seal cleanly.', interval_days: 180, priority: 'medium' },
    { name: 'Check Toilet for Silent Leaks', description: 'Add a few drops of food coloring to the tank. Wait 15 minutes without flushing — if color appears in the bowl, the flapper is leaking.', interval_days: 180, priority: 'medium' },
    { name: 'Inspect Washing Machine Hoses', description: 'Check rubber supply hoses for bulges, cracks, or brittleness. Replace rubber hoses with braided stainless steel every 3-5 years.', interval_days: 180, priority: 'high' },
    { name: 'Clean Faucet Aerators', description: 'Unscrew aerators from kitchen and bathroom faucets. Soak in vinegar to dissolve mineral deposits. Scrub and reinstall.', interval_days: 180, priority: 'low' },
    { name: 'Flush Supply Lines', description: 'Open each faucet fully for 30 seconds to flush sediment. Focus on fixtures that are used infrequently.', interval_days: 180, priority: 'low' },
    { name: 'Test Sump Pump', description: 'Pour a bucket of water into the sump pit to trigger the float switch. Verify the pump activates and drains the water. Check the discharge line for blockages.', interval_days: 90, priority: 'high' },
    { name: 'Inspect Caulking Around Tubs & Showers', description: 'Check caulk and grout around tubs, showers, and backsplashes for cracks or gaps. Re-caulk to prevent water damage behind walls.', interval_days: 180, priority: 'medium' },
    { name: 'Clean Drain Stoppers & Screens', description: 'Remove drain stoppers and screens from showers and sinks. Clear hair and debris. Clean with vinegar and baking soda.', interval_days: 90, priority: 'low' },
    { name: 'Check Water Pressure', description: 'Attach a pressure gauge to an outdoor spigot. Normal range is 40-60 PSI. Over 80 PSI can damage pipes and fixtures — consider a pressure regulator.', interval_days: 365, priority: 'medium' },
  ],
  electrical: [
    { name: 'Test GFCI Outlets', description: 'Press the TEST button on all GFCI outlets (kitchens, bathrooms, garage, outdoor). The RESET button should pop out. If it doesn\'t trip, replace it.', interval_days: 90, priority: 'high' },
    { name: 'Test Smoke Detectors', description: 'Press the test button on every smoke detector. Replace batteries annually. Replace the entire unit every 10 years.', interval_days: 180, priority: 'high' },
    { name: 'Test Carbon Monoxide Detectors', description: 'Press the test button on all CO detectors. Check expiration date — most last 5-7 years. Replace batteries annually.', interval_days: 180, priority: 'high' },
    { name: 'Inspect Breaker Panel', description: 'Open the panel door and visually inspect for scorch marks, corrosion, or a burning smell. Check that breakers are properly labeled. Do NOT touch bus bars.', interval_days: 365, priority: 'medium' },
    { name: 'Check for Warm or Discolored Outlets', description: 'Feel outlets and switch plates for unusual warmth. Look for discoloration or melting. These can indicate loose wiring or overloaded circuits — call an electrician.', interval_days: 180, priority: 'high' },
    { name: 'Test Arc-Fault Breakers (AFCI)', description: 'Press the TEST button on AFCI breakers in the panel. They should trip immediately. Reset after testing. Required in bedrooms and living areas.', interval_days: 180, priority: 'medium' },
    { name: 'Check Fire Extinguishers', description: 'Verify the pressure gauge is in the green zone. Check that the pin and tamper seal are intact. Shake dry chemical extinguishers to prevent compaction.', interval_days: 180, priority: 'high' },
    { name: 'Inspect Outdoor Outlets & Lighting', description: 'Check all outdoor outlets for proper weatherproof covers. Test GFCI function. Replace burned-out bulbs and check light fixture seals.', interval_days: 180, priority: 'medium' },
    { name: 'Check Surge Protectors', description: 'Verify surge protector indicator lights are active. Replace power strips and surge protectors every 3-5 years — they degrade with each surge.', interval_days: 365, priority: 'low' },
    { name: 'Inspect Extension Cord Usage', description: 'Make sure no extension cords are used as permanent wiring. Check for frayed cords, pinched wires, or cords running under rugs or through walls.', interval_days: 365, priority: 'medium' },
  ],
  septic: [
    { name: 'Schedule Tank Pumping', description: 'Have the septic tank pumped by a licensed service. Typical schedule is every 3-5 years depending on household size and tank capacity.', interval_days: 1095, priority: 'high' },
    { name: 'Inspect Tank Baffles', description: 'During pumping, have the technician inspect inlet and outlet baffles. Damaged baffles allow solids into the drain field.', interval_days: 1095, priority: 'high' },
    { name: 'Check for Signs of Drain Field Problems', description: 'Walk the drain field area. Look for soggy spots, sewage odor, or unusually lush green patches — these indicate potential failure.', interval_days: 180, priority: 'medium' },
    { name: 'Inspect Tank Lid & Risers', description: 'Check that the septic tank lid is secure and not cracked. Verify risers are sealed and above grade for easy access.', interval_days: 365, priority: 'medium' },
    { name: 'Monitor Water Usage', description: 'Track household water usage. Excessive water overwhelms the septic system. Fix running toilets and leaky faucets promptly. Spread laundry loads throughout the week.', interval_days: 90, priority: 'low' },
    { name: 'Check Effluent Filter', description: 'If your system has an effluent filter (at the outlet baffle), clean it by hosing it off. A clogged filter can cause backups.', interval_days: 365, priority: 'high' },
    { name: 'Review Septic-Safe Products', description: 'Verify that household cleaners, soaps, and toilet paper are septic-safe. Avoid bleach-heavy products, antibacterial soaps, and flushable wipes.', interval_days: 365, priority: 'low' },
    { name: 'Protect the Drain Field', description: 'Ensure no vehicles park on the drain field. Keep trees and deep-rooted plants at least 30 feet away. Don\'t build structures over it.', interval_days: 365, priority: 'medium' },
  ],
  'roof-gutters': [
    { name: 'Clean Gutters & Downspouts', description: 'Remove leaves, debris, and sediment from all gutters. Flush downspouts with a hose to check for clogs. Best done in fall and spring.', interval_days: 180, priority: 'high' },
    { name: 'Inspect Roof from Ground', description: 'Use binoculars to scan the roof for missing, cracked, or curling shingles. Look for sagging areas or visible damage after storms.', interval_days: 180, priority: 'medium' },
    { name: 'Check Flashing & Seals', description: 'Inspect flashing around chimneys, vents, skylights, and roof valleys. Look for rust, gaps, or lifted edges that could let water in.', interval_days: 365, priority: 'high' },
    { name: 'Inspect Attic for Leaks', description: 'Check the attic after heavy rain for water stains, damp insulation, or daylight showing through. Look around vents and chimneys.', interval_days: 180, priority: 'medium' },
    { name: 'Trim Overhanging Branches', description: 'Cut back tree branches within 6 feet of the roof. Overhanging branches drop debris, promote moss, and can damage shingles in storms.', interval_days: 365, priority: 'medium' },
    { name: 'Check Gutter Fasteners & Slope', description: 'Verify gutters are firmly attached and sloping toward downspouts. Sagging gutters hold standing water and can pull away from the fascia.', interval_days: 365, priority: 'low' },
    { name: 'Inspect Downspout Extensions', description: 'Make sure downspouts discharge water at least 4-6 feet from the foundation. Add splash blocks or extensions if needed.', interval_days: 180, priority: 'medium' },
    { name: 'Check for Moss or Algae Growth', description: 'Look for moss, algae, or lichen on the roof surface. These retain moisture and degrade shingles. Treat with a moss killer or zinc strips.', interval_days: 365, priority: 'low' },
    { name: 'Professional Roof Inspection', description: 'Schedule a professional roof inspection. Recommended every 3-5 years or after major storms. They\'ll check structural integrity and remaining life.', interval_days: 1095, priority: 'high' },
  ],
  appliances: [
    { name: 'Clean Dryer Vent & Duct', description: 'Disconnect the dryer duct and clean lint from the full length of the vent to the exterior. Lint buildup is a leading cause of house fires.', interval_days: 180, priority: 'high' },
    { name: 'Clean Dryer Lint Trap Housing', description: 'Remove the lint screen and vacuum inside the housing. Wash the screen with soap and water to remove dryer sheet residue that blocks airflow.', interval_days: 90, priority: 'medium' },
    { name: 'Clean Dishwasher Filter', description: 'Remove and clean the dishwasher filter (usually at the bottom). Rinse under running water and scrub with a soft brush. Food buildup causes odors and poor cleaning.', interval_days: 90, priority: 'medium' },
    { name: 'Clean Dishwasher Interior', description: 'Run an empty cycle with a cup of white vinegar on the top rack, followed by a baking soda sprinkle on the bottom. Cleans residue and eliminates odors.', interval_days: 90, priority: 'low' },
    { name: 'Clean Refrigerator Coils', description: 'Pull the fridge out and vacuum or brush the condenser coils (usually on the back or underneath). Dirty coils force the compressor to work harder.', interval_days: 180, priority: 'medium' },
    { name: 'Check Refrigerator Door Seals', description: 'Close the door on a dollar bill — if it slides out easily, the gasket needs replacing. Check all fridge and freezer door seals.', interval_days: 180, priority: 'low' },
    { name: 'Flush Ice Maker Line', description: 'Shut off the ice maker, disconnect the water line, and flush it. This removes mineral buildup and keeps ice tasting fresh.', interval_days: 365, priority: 'low' },
    { name: 'Clean Range Hood Filter', description: 'Remove the range hood grease filter and soak in hot soapy water or run through the dishwasher. A clogged filter reduces ventilation.', interval_days: 90, priority: 'medium' },
    { name: 'Inspect Washing Machine', description: 'Run a clean cycle with washer cleaner or vinegar. Wipe the door gasket (front-loaders) to prevent mold. Check hoses for bulges.', interval_days: 90, priority: 'medium' },
    { name: 'Clean Garbage Disposal', description: 'Grind ice cubes and citrus peels to clean the blades. Pour baking soda and vinegar down the drain, then flush with hot water.', interval_days: 90, priority: 'low' },
  ],
  exterior: [
    { name: 'Inspect Foundation for Cracks', description: 'Walk the perimeter and check the foundation for new cracks, shifting, or water staining. Hairline cracks are normal; widening cracks need professional assessment.', interval_days: 180, priority: 'high' },
    { name: 'Check Grading & Drainage', description: 'Verify the ground slopes away from the foundation on all sides (6 inches of drop over the first 10 feet). Poor grading directs water toward the foundation.', interval_days: 365, priority: 'medium' },
    { name: 'Inspect Siding & Exterior Walls', description: 'Look for cracks, holes, loose sections, or rot in siding. Check paint for peeling or bubbling. Address gaps where moisture or pests can enter.', interval_days: 365, priority: 'medium' },
    { name: 'Clean Siding & Exterior Surfaces', description: 'Power wash or hand-wash siding, brick, and stucco. Remove mildew, dirt, and cobwebs. Clean from bottom to top to avoid streaking.', interval_days: 365, priority: 'low' },
    { name: 'Inspect & Reseal Driveway', description: 'Check asphalt or concrete driveway for cracks. Fill cracks with appropriate filler. Reseal asphalt driveways every 2-3 years.', interval_days: 730, priority: 'medium' },
    { name: 'Inspect Deck or Patio', description: 'Check for loose boards, popped nails, rot, or splintering. Test structural posts for firmness. Clean and reseal wood decks every 1-2 years.', interval_days: 365, priority: 'medium' },
    { name: 'Check Exterior Caulking & Weatherstripping', description: 'Inspect caulk around windows, doors, and penetrations. Replace cracked or missing caulk. Check door weatherstripping for gaps.', interval_days: 365, priority: 'medium' },
    { name: 'Inspect Outdoor Faucets & Spigots', description: 'Check hose bibs for drips or leaks. Before winter, disconnect hoses and shut off interior valves to outdoor faucets to prevent freezing.', interval_days: 180, priority: 'medium' },
    { name: 'Test Exterior Drainage Systems', description: 'Run water through French drains, channel drains, or dry wells. Check for clogs or pooling. Clean drain grates of debris.', interval_days: 365, priority: 'low' },
  ],
  'garage-door': [
    { name: 'Lubricate Moving Parts', description: 'Apply white lithium grease or silicone spray to hinges, rollers, springs, and the track. Do NOT use WD-40 — it\'s a degreaser, not a lubricant.', interval_days: 180, priority: 'medium' },
    { name: 'Test Auto-Reverse Safety', description: 'Place a 2x4 flat on the ground under the door. Close the door — it should reverse when it contacts the board. Also test the photo-eye sensors by waving an object through the beam.', interval_days: 90, priority: 'high' },
    { name: 'Inspect Rollers', description: 'Check nylon or steel rollers for chips, cracks, or wear. Worn rollers make the door noisy and can cause it to bind. Replace every 5-7 years.', interval_days: 365, priority: 'medium' },
    { name: 'Check Weatherstripping', description: 'Inspect the rubber seal at the bottom of the door and the weatherstripping around the frame. Replace if cracked, brittle, or letting in drafts and water.', interval_days: 365, priority: 'low' },
    { name: 'Inspect Cables & Springs', description: 'Visually inspect lift cables for fraying and springs for gaps or elongation. Do NOT attempt to repair springs yourself — they are under extreme tension. Call a professional.', interval_days: 180, priority: 'high' },
    { name: 'Tighten Hardware', description: 'Check and tighten all bolts and brackets on the door and track system. Vibration from daily use loosens hardware over time.', interval_days: 365, priority: 'low' },
    { name: 'Test Door Balance', description: 'Disconnect the opener and manually lift the door halfway. It should stay in place. If it falls or rises, the springs need adjustment by a professional.', interval_days: 365, priority: 'medium' },
    { name: 'Clean & Align Photo-Eye Sensors', description: 'Wipe the photo-eye lenses with a soft cloth. Check that both sensors are aligned (indicator lights steady, not blinking). Misaligned sensors prevent the door from closing.', interval_days: 180, priority: 'medium' },
  ],
};
